#!/bin/bash

# Are we root? If so, stop immediately.
if [ `id -u` == 0 ]; then
	echo "Do not run dockit as root. Exiting."
	exit 1
fi

# Script Execution
if [ "$1" == "create" ] || [ "$1" == "-c" ]; then
	docker run -it -d --name=$2 -v $HOME:/root fedora /bin/bash && echo "Container created. Enter the container by executing: \"dockit enter $2\"!"
elif [ "$1" == "enter" ] || [ "$1" == "-e" ]; then
	docker start $2 && docker exec -it $2 /bin/bash
elif [ "$1" == "stop" ] || [ "$1" == "-s" ]; then
	docker stop $2
elif [ "$1" == "restart" ] || [ "$1" == "-r" ]; then
	docker stop $2 && docker start $2
elif [ "$1" == "remove" ] || [ "$1" == "-R" ]; then
	docker stop $2; docker rm $2
elif [ "$1" == "list" ] || [ "$1" == "-l" ]; then
	docker ps -a

# If nothing else, just show the help text
else
	bold=$(tput bold)
	normal=$(tput sgr0)
	echo "${bold}usage:${normal} dockit <operation> [...]"
	echo -e "${bold}operations:${normal}\n"
	echo "${bold}dockit {create -c} <name>${normal}"
	echo -e "Create a container called <name>.\n"
	echo "${bold}dockit {enter -e} <name>${normal}"
	echo -e "Enter the container <name>.\n"
	echo "${bold}dockit {stop -s} <name>${normal}"
	echo -e "Stop the running container <name>.\n"
	echo "${bold}dockit {restart -r} <name>${normal}"
	echo -e "Restart the container <name>.\n"
	echo "${bold}dockit {remove -R} <name>${normal}"
	echo -e "Remove the container <name>. If the container is currently running, it will be stopped first.\n"
	echo "${bold}dockit {list -l}${normal}"
	echo -e "List all available containers.\n"
fi